// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikzomyiasnlspaaiwcao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlrem9teWlhc25sc3BhYWl3Y2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMDk3NTYsImV4cCI6MjA4NjY4NTc1Nn0.CzpeGd91kxoEpdDK_q8bMi0htLMR5w0lGkthAwBNJA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});